# fly.toml app configuration file generated for taxon on 2023-04-26T23:28:02-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "taxon"
kill_signal = "SIGTERM"
kill_timeout = 5
primary_region = "ord"
processes = []

[build]

[env]
  PHX_HOST = "taxon.fly.dev"
  PORT = "8080"
  DATABASE_PATH = "/mnt/taxon_db/taxon.db"

[mounts]
  source="taxon_db"
  destination="/mnt/taxon_db"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 1000
    soft_limit = 1000
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
